name: Test
on: push

jobs:
  common-test:
    name: Run Common Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 23.2
      - name: Run Common Test
        run: rebar3 ct
