name: Test
on: [push, pull_request]

jobs:
  common-test:
    name: Run Common Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21, 22, 23, 24, 25, 26, 27, 28]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Common Test
        run: |
             rebar3 xref
             rebar3 dialyzer
             rebar3 ct
