name: Test
on: [push, pull_request]

jobs:
  common-test:
    name: Run Common Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21.3, 22.3, 23.2.7.0, 24.3.4.5, 25.1]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Common Test
        run: |
             rebar3 xref
             rebar3 dialyzer
             rebar3 ct
